// <auto-generated />
namespace MeetingCoordinator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initial_electric_boogaloo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_electric_boogaloo));
        
        string IMigrationMetadata.Id
        {
            get { return "201604221748379_initial_electric_boogaloo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
