// <auto-generated />
namespace MeetingCoordinator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Init_The_Return : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init_The_Return));
        
        string IMigrationMetadata.Id
        {
            get { return "201604221737187_Init_The_Return"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
